-- Add PropertyType enum and payment methods
CREATE TYPE "PropertyType" AS ENUM ('HOTEL', 'RESORT', 'SERVICE_APARTMENT', 'HOUSE', 'VILLA', 'BOUTIQUE', 'HOMESTAY');

ALTER TABLE "hotels" ADD COLUMN IF NOT EXISTS "propertyType" "PropertyType" NOT NULL DEFAULT 'HOTEL';

ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'UPI';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'ALIPAY';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'THAI_QR';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'PAY_AT_HOTEL';
