export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PARTNER: 'PARTNER',
  RECEPTIONIST: 'RECEPTIONIST',
  GUEST: 'GUEST',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Hotels
  HOTEL_CREATE: 'hotel:create',
  HOTEL_READ: 'hotel:read',
  HOTEL_UPDATE: 'hotel:update',
  HOTEL_DELETE: 'hotel:delete',
  HOTEL_APPROVE: 'hotel:approve',

  // Rooms
  ROOM_CREATE: 'room:create',
  ROOM_READ: 'room:read',
  ROOM_UPDATE: 'room:update',
  ROOM_DELETE: 'room:delete',

  // Pricing
  PRICING_READ: 'pricing:read',
  PRICING_UPDATE: 'pricing:update',

  // Bookings
  BOOKING_CREATE: 'booking:create',
  BOOKING_READ: 'booking:read',
  BOOKING_UPDATE: 'booking:update',
  BOOKING_CANCEL: 'booking:cancel',

  // PMS
  PMS_CHECKIN: 'pms:checkin',
  PMS_CHECKOUT: 'pms:checkout',
  PMS_FOLIO: 'pms:folio',
  PMS_ROOM_STATUS: 'pms:room_status',

  // Payments
  PAYMENT_CREATE: 'payment:create',
  PAYMENT_READ: 'payment:read',
  PAYMENT_REFUND: 'payment:refund',

  // Admin
  ADMIN_USERS: 'admin:users',
  ADMIN_ANALYTICS: 'admin:analytics',
  ADMIN_AUDIT: 'admin:audit',
  ADMIN_BILLING: 'admin:billing',

  // Finance
  FINANCE_READ: 'finance:read',
  FINANCE_SETTLE: 'finance:settle',

  // Analytics
  ANALYTICS_READ: 'analytics:read',

  // Uploads
  UPLOAD_CREATE: 'upload:create',
  UPLOAD_READ: 'upload:read',

  // Notifications
  NOTIFICATION_READ: 'notification:read',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.HOTEL_READ,
    PERMISSIONS.HOTEL_UPDATE,
    PERMISSIONS.HOTEL_APPROVE,
    PERMISSIONS.HOTEL_DELETE,
    PERMISSIONS.ROOM_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.ADMIN_USERS,
    PERMISSIONS.ADMIN_ANALYTICS,
    PERMISSIONS.ADMIN_AUDIT,
    PERMISSIONS.ADMIN_BILLING,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.UPLOAD_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  PARTNER: [
    PERMISSIONS.HOTEL_CREATE,
    PERMISSIONS.HOTEL_READ,
    PERMISSIONS.HOTEL_UPDATE,
    PERMISSIONS.ROOM_CREATE,
    PERMISSIONS.ROOM_READ,
    PERMISSIONS.ROOM_UPDATE,
    PERMISSIONS.ROOM_DELETE,
    PERMISSIONS.PRICING_READ,
    PERMISSIONS.PRICING_UPDATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.PMS_CHECKIN,
    PERMISSIONS.PMS_CHECKOUT,
    PERMISSIONS.PMS_FOLIO,
    PERMISSIONS.PMS_ROOM_STATUS,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.UPLOAD_CREATE,
    PERMISSIONS.UPLOAD_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_SETTLE,
  ],
  RECEPTIONIST: [
    PERMISSIONS.HOTEL_READ,
    PERMISSIONS.ROOM_READ,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.PMS_CHECKIN,
    PERMISSIONS.PMS_CHECKOUT,
    PERMISSIONS.PMS_FOLIO,
    PERMISSIONS.PMS_ROOM_STATUS,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  GUEST: [
    PERMISSIONS.HOTEL_READ,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const HOTEL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED',
} as const;

export const ROOM_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  DIRTY: 'DIRTY',
  MAINTENANCE: 'MAINTENANCE',
  BLOCKED: 'BLOCKED',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
} as const;

export const API_PREFIX = '/api/v1';

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
